MAP = {
    # Keywords
    'Шмекерия': 'False',
    'Пусто': 'None',
    'Верно': 'True',
    'и': 'and',
    'куту': 'as',
    'мигар': 'assert',
    'часка': 'async',
    'чекай': 'await',
    'кини': 'break',
    'чешит': 'class',
    'маай': 'continue',
    'напраи': 'def',
    'маани': 'del',
    'илипа': 'elif',
    'епа': 'else',
    'еш': 'except',
    'разгеле': 'finally',
    'за': 'for',
    'из': 'from',
    'вънка': 'global',
    'ако': 'if',
    'земи': 'import',
    'у': 'in',
    'е': 'is',
    'пустиняк': 'lambda',
    'вън': 'nonlocal',
    'не': 'not',
    'ели': 'or',
    'раат': 'pass',
    'връй': 'raise',
    'връни': 'return',
    'проай': 'try',
    'дорде': 'while',
    'със': 'with',
    'метни': 'yield',
    # Builtins
    'мъцни': 'print',
    'Заглава': 'Exception',
    'КвоСтана': 'AssertionError',
    'ае': 'quit()',
    'измежду': 'range',
    'цело': 'int',
    'тоа': 'type',
    # Operators
    'бетер': '>',
    'нема': '<',
    'колко': '==',
}


REVERSE_MAP = {val: key for key, val in MAP.items()}
